apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-html
  namespace: default
data:
  index.html: |
    <!-- index.html -->
    <html>
      <head><title>Custom Page</title></head>
      <body>
        <h1>Hellooooooooo from custom Nginx!</h1>
      </body>
    </html>

