apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sanjay-s-new/kubernetis.git
    targetRevision: main
    path: .   # <- Replace this with the folder containing your manifests, e.g. '.' or 'manifests'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

